name: CI API Tests
on:
  push:
    branches: ["lesson30_api_automation"]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependecies
        run: npm ci
      - name: Run playwright test
        run: npm run api_tests
